<?php

/**
 * @file
 * Install, update and uninstall functions for the Message Broker Producer module.
 *
 */

/**
 * Implements hook_requirements().
 */
function message_broker_producer_requirements($phase) {
  $requirements = array();

  if ($phase == 'runtime') {

    $library = libraries_detect('messagebroker-phplib');

    if (empty($library['installed'])) {
      $requirements['messagebroker-phplib'] = array(
        'title' => t('Message Broker PHP Library'),
        'value' => t('Any version'),
        'severity' => REQUIREMENT_ERROR,
        'description' => t(
          'You need to download the !messagebroker, extract the archive and place the message-broker-php-lib directory in the %path directory on your server.',
          array('!messagebroker' => l(t('Message Broker PHP Library'), $library['download url']), '%path' => 'sites/all/libraries')
        ),
      );
    }
  }
  return $requirements;
}

 /**
 * Deletes exchange_cache and queue_cache system variables
 */
function message_broker_producer_update_7001(&$sandbox) {

  // Exchange
  variable_del('message_broker_producer_exchange_cache_name');
  variable_del('message_broker_producer_exchange_cache_type');
  variable_del('message_broker_producer_exchange_cache_passive');
  variable_del('message_broker_producer_exchange_cache_durable');
  variable_del('message_broker_producer_exchange_cache_auto_delete');

  // Queue
  variable_del('message_broker_producer_queue_campaign_cache_name');
  variable_del('message_broker_producer_queue_campaign_cache_passive');
  variable_del('message_broker_producer_queue_campaign_cache_durable');
  variable_del('message_broker_producer_queue_campaign_cache_exclusive');
  variable_del('message_broker_producer_queue_campaign_cache_auto_delete');
  variable_del('message_broker_producer_queue_campaign_cache_binding_key');

}
